### ISSUE TITLE
EPIC: Conditional Items (EnableWhen)

### ISSUE THREAD

**Issue by kennethmyhra** [helsenorge/structor#169]
* [x] `question` - The question that determines whether item is enabled
* [x] `operator` - Specifies the criteria by which the question is enabled
  * `=`
  * `!=`
  *  `>`
  *  `>=`
  * `<`
  * `<=`
  * `exists` - If the operator is exists the answer value must be boolean. The exists operator tests if an answer exists
* [x] `answer` - Value for question comparison based on operator
  * `answerBoolean` - Only the operator `=` and `exists` are allowed
  * `answerDecimal`
  * `answerDate`
  * `answerDateTime`
  * `answerTime`
  * `answerString` - Only the operator `=`  is allowed
  * `answerCoding` - Only the operator `=`  is allowed
  * `answerQuantity`
* [x] `enableBehavior` - Controls how multiple enableWhen values are interpreted - whether all or any must be true.

**Comment by losolio** [comment]
Closed by a33a6f2bfb0f76213b31326a5cc209fcb40a7ba2
